In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Load the CSV file
df = pd.read_csv("noaa - 5000.csv")

# Convert string dates to datetime objects
df["date"] = pd.to_datetime(
    df["date"],
    errors="coerce"
)

# Check the converted dates
print(df["date"].head())
print(df["date"].dtype)

# Check for invalid dates
print("Invalid dates:", df["date"].isna().sum())

0   2025-07-04
1   2025-04-30
2   2025-04-19
3   2025-04-20
4   2025-03-05
Name: date, dtype: datetime64[us]
datetime64[us]
Invalid dates: 0

In [4]:
df = df.dropna(subset=["date"])

In [4]:
df = df.sort_values("date")

In [5]:
df = df.set_index("date")

In [ ]:
continuous_dates = pd.date_range(
    start=df.index.min(),
    end=df.index.max(),
    freq="D")

In [8]:
df = df.set_index("date")

In [9]:
# Select all data from a year
df.loc["2020"]

Empty DataFrame
Columns: [stn, wban, year, mo, da, temp, count_temp, dewp, count_dewp, slp, count_slp, stp, count_stp, visib, count_visib, wdsp, count_wdsp, mxpsd, gust, max, flag_max, min, flag_min, prcp, flag_prcp, sndp, fog, rain_drizzle, snow_ice_pellets, hail, thunder, tornado_funnel_cloud]
Index: []

[0 rows x 32 columns]

In [14]:
# Select all data from a month
df.loc["2020-01"]

Empty DataFrame
Columns: [stn, wban, year, mo, da, temp, count_temp, dewp, count_dewp, slp, count_slp, stp, count_stp, visib, count_visib, wdsp, count_wdsp, mxpsd, gust, max, flag_max, min, flag_min, prcp, flag_prcp, sndp, fog, rain_drizzle, snow_ice_pellets, hail, thunder, tornado_funnel_cloud]
Index: []

[0 rows x 32 columns]

In [6]:
# Reindex the data using the continuous calendar
df = df.reindex(continuous_dates)

# Name the index
df.index.name = "date"

print(df.head())
print(type(df.index))

            stn  wban date  year  mo  da  temp  count_temp  dewp  count_dewp  \
date
1970-01-01  NaN   NaN  NaT   NaN NaN NaN   NaN         NaN   NaN         NaN

            ...  flag_min  prcp  flag_prcp  sndp  fog  rain_drizzle  \
date        ...
1970-01-01  ...       NaN   NaN        NaN   NaN  NaN           NaN

            snow_ice_pellets  hail  thunder  tornado_funnel_cloud
date
1970-01-01               NaN   NaN      NaN                   NaN

[1 rows x 33 columns]
<class 'pandas.DatetimeIndex'>